### ISSUE TITLE
Pretty print precedence for interval expressions

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#514] opened 2022-09-17 06:59 UTC
![image](https://user-images.githubusercontent.com/16398479/190844822-81d5c88e-b36d-49e0-af46-1b8a2d354bd8.png)

Should have parenthesis

**Comment by wsx-ucb** [comment] 2022-09-19 06:19
Are there any concrete cases for this issue?
For the case in the picture, is that indented to be `(p i) /\ i` or `p (i /\ i)`?
I've tested the second case in REPL and it seems that parentheses are added correctly:
```
> def test (a : A) (p : a = a) => \i => p (i /\ i)
def test {A : Type 0} (a : A) (p : a = a) : I → A ⇒ λ i ⇒ p (i /\ i)
```

**Comment by ice1000** [comment] 2022-09-19 06:21
@wsx-ucb Latter. Idk why they're like this

**Comment by wsx-ucb** [comment] 2022-09-19 06:27
Are you sure? If the term is indeed `p (i /\ i)`, then why is it an `Elim.App` instead of `Elim.PathApp`?
And it seems that in REPL the only former `(p i) /\ i` will be printed as `p i /\ i`:
```
> def test (i : I) (p : i = i) => \j => (p j) /\ j
def test (i : I) (p : i = i) : I → I ⇒ λ j ⇒ p j /\ j
```

**Comment by ice1000** [comment] 2022-09-19 06:29
Interesting. Can you try pp an `Elim.PathApp`?

**Comment by ice1000** [comment] 2022-09-19 06:31
> Are you sure? If the term is indeed `p (i /\ i)`, then why is it an `Elim.App` instead of `Elim.PathApp`?

Clearly a bug

**Comment by ice1000** [comment] 2022-09-19 06:32
Is it because that it's an `Elim.App` so that it's not parenthesized?

**Comment by ice1000** [comment] 2022-09-19 06:33
@wsx-ucb I kinda get it. Is it because it's printing concrete instead of core/

**Comment by ice1000** [comment] 2022-09-19 06:33
https://github.com/aya-prover/aya-dev/blob/82ade1d88da70e92c9c74f4120bec0e45c5077c3/base/src/main/java/org/aya/distill/CoreDistiller.java#L167

It doesn't handle parenthesis at all

**Comment by wsx-ucb** [comment] 2022-09-19 06:35
Likely to be the issue here.
Does the REPL always use concrete when printing the result?

**Comment by ice1000** [comment] 2022-09-19 06:36
> Likely to be the issue here. Does the REPL always use concrete when printing the result?

Idk

**Comment by ice1000** [comment] 2022-09-19 06:38
![image](https://user-images.githubusercontent.com/16398479/190961772-12fe81f6-1d3d-45e7-ba2a-b31e6c9e88a9.png)
Returns `Def`

**Comment by ice1000** [comment] 2022-09-19 06:40
@wsx-ucb try
```
def test (p : I ->I) : I → I ⇒ λ j ⇒ p (j /\ j)
```

**Comment by wsx-ucb** [comment] 2022-09-19 06:43
Still works as intended:
```
> def test (p : I -> I) : I → I ⇒ λ j ⇒ p (j /\ j)
def test (p : I → I) : I → I ⇒ λ j ⇒ p (j /\ j)
```

**Comment by ice1000** [comment] 2022-09-19 06:45
@wsx-ucb What is your definition of `/\`? Can you use something like `open import Primitives using (intervalInv as ~)`

Maybe I was wrong on using REPL to test, you should use the library

**Comment by ice1000** [comment] 2022-09-19 06:45
Is it possible to use `new` to manually construct the term?

**Comment by imkiva** [comment] 2022-09-19 06:48
Try this code:

```
prim I
prim intervalInv
prim intervalMin
prim coe
def inline ~ => intervalInv
def inline infix /\ => intervalMin
def Path (A : I -> Type) (a : A 0) (b : A 1) : Type => [| i |] A i {| ~ i := a | i := b |}
def Eq (A : Type) (a b : A) : Type => Path (\ i => A) a b
variable A : Type
def infix = {A : Type} => Eq A
def idp {a : A} : a = a => \i => a
def J {a : A} (B : Pi (b : A) -> a = b -> Type)
      (r : B a (\x => a)) {b : A} (p : a = b) : B b p =>
      coe (\ i => B (p i) (\j => p (j /\ i))) 0 r
```

Setting a breakpoint at `ExprTycker#checkBoundaries` and see the `applied`

![image](https://user-images.githubusercontent.com/9902643/190963081-666b6f08-fead-4e14-879e-86ae093ff612.png)

**Comment by wsx-ucb** [comment] 2022-09-19 06:49
> What is your definition of `/\`?

`def infix /\\ => intervalMin`

> Can you use something like `open import Primitives using (intervalInv as ~)`

I've tried doing this, but despite the REPL being in the correct directory, I got the error
```
The module name `Primitives' is not found
```
Maybe there is a step missing?

**Comment by ice1000** [comment] 2022-09-19 06:49
Bingo!!

**Comment by imkiva** [comment] 2022-09-19 06:49
> Are you sure? If the term is indeed `p (i /\ i)`, then why is it an `Elim.App` instead of `Elim.PathApp`?

It is a bug when this issue was opened. Now it is indeed a `PathApp`

**Comment by imkiva** [comment] 2022-09-19 06:50
Looks like `Mula` should respect `outer`

**Comment by ice1000** [comment] 2022-09-19 06:52
@wsx-ucb can you try @imkiva 's snippet

**Comment by imkiva** [comment] 2022-09-19 06:52
I propose a distiller unit test with a manually created `PathApp`

**Comment by wsx-ucb** [comment] 2022-09-19 06:56
Thanks for all the help!
I've tried the snippet and can reproduce the issue now.
Changing the logic for `Mula` in `CoreDistiller` into
```
checkParen(outer, formula(options, mula.asFormula()), Outer.BinOp);
```
seems to fix the issue.

**Comment by ice1000** [comment] 2022-09-19 06:57
@wsx-ucb Are you sure binop

**Comment by ice1000** [comment] 2022-09-19 06:58
@wsx-ucb Can you try more like a and b or c and d? Do they work as intended?

**Comment by wsx-ucb** [comment] 2022-09-19 07:07
> Are you sure binop

This way `checkParen` should only omit parenthesis when `outer` binds strictly looser than `Outer.BinOp`, which is the intended result, right?

> Can you try more like a and b or c and d? Do they work as intended?

Nice suggestion! The result would be something like `p (j /\ i \/ i /\ j)`, which is problematic inside the formula.
I'll chage how formula itself is handled in `CoreDistiller` to fix this.

**Comment by wsx-ucb** [comment] 2022-09-19 07:51
I've just pushed a quick fix for this issue.
It changed some methods in `BaseDistiller`, which I'm not sure if that fits with other distiller code.

**Closed** 2022-09-20 15:04 UTC
Labels: bug, pretty print, cubical
